--EXAMPLES USING WEAK AND STRONG REF CURSOR
DECLARE 
TYPE TYP_REF IS REF CURSOR;
TYP TYP_REF;

TYPE TYP_REF2 IS REF CURSOR RETURN EMP%ROWTYPE;
TYP2 TYP_REF2;

BEGIN
  OPEN TYP2 FOR SELECT * FROM EMP;
  /*LOOP
    FETCH TYP2 INTO EMP;
    EXIT WHEN TYP2%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(TYP2.ENAME);
    END LOOP;*/
    DBMS_OUTPUT.PUT_LINE(TYP2.ENAME);
  CLOSE TYP2;
  END;
  
------------------
--FUNCTION TO RETURN NO OF SUNDAYS BETWEEN TWO DATES FROM DATE AND TO DATE
SELECT TO_CHAR(TO_DATE('24-05-2003','DD-MM-YYYY')-TO_DATE('20-05-2003','DD-MM-YYYY'),'') FROM DUAL

--'RED,GREEN,YELLOW,PINK,ORANGE,GREY,BLUE' --PROGRAM TO SEPARATE THE COMMA VALUES USING PROCEDURE
SELECT SUBSTR('RED,GREEN,PINK,BLUE,YELLOW,ORANGE,BLACK',
INSTR('RED,GREEN,PINK,BLUE,YELLOW,ORANGE,BLACK',',',1,3)+1,
INSTR('RED,GREEN,PINK,BLUE,YELLOW,ORANGE,BLACK',',',1,4)-
INSTR('RED,GREEN,PINK,BLUE,YELLOW,ORANGE,BLACK',',',1,3)-1) FROM DUAL

SELECT INSTR('RED,GREEN,PINK,BLUE,YELLOW,ORANGE,BLACK',',') FROM DUAL

DECLARE
  X VARCHAR2(1000) := '4567329188567';
BEGIN
  DBMS_OUTPUT.PUT_LINE(X);
  DBMS_OUTPUT.PUT_LINE('-----');
  FOR I IN 1 .. LENGTH(X) LOOP
    DBMS_OUTPUT.PUT_LINE(SUBSTR(X, I, 1));
  END LOOP;
END;






