--1. SYSTEM SHOULD NOT ALLOW TO JOIN NEW EMP IF HIS COMM IS MORE THAN HIS SAL
--2. IF ANY EMP IS JOINING WITHOUT COMM OR MANAGER EMP CANNOT JOIN
--3. IF EMP SAL IS MODIFIED IT SHOULD BE INCREASE ONLY,IF DECREASE FOR ONLY 1OTH DEPT
--4. IF EMP SAL INCREASED OR DECREASED COMM SHOULD BE UPDATE 20% OF NEW SAL
--5. IF EMP NAME AND SAL IS MODIFIEID THEN ONLY COMM SHOULD BE CHANGED, IF ONLY NAME IS CHANGED
--SYSTEM SHOULD NOT ALLOW, IF SAL IS MODIFIED, SYSTEM SHOULD NOT ALLOW

SELECT * FROM EMP
INSERT INTO EMP (ENAME,COMM,MGR) VALUES('REDDY',5000,0)
UPDATE EMP SET SAL = 1000 WHERE EMPNO = 7369
