--1.
--IN sal grade table SAT AND SUN NOT INSERT --BEFORE STATEMENT
--IF GRADE NO CHANGE --SYSTEM SHOULD NOT ACCEPT- BEFORE ROW LEVEL

------------
--2.
--COMPOUND TRIGGER
----EMPNO,ENAME,SAL,JOB,DEPTNO--RECORD VARIABLE 
-----RECORD--COLLECTION ON RECORD
--SUB TYPE---

--BEFORE ROW LEVEL--TRIGGER --IN THE COMPOUND
---DELETE --COLLECTION 

--AFTER STMT--LEVEL--
---COLLETION DATE LOOP--EMP INSERT 

--3.
--CREATE A DUMMY EMP TABLE AND STORE OLD VALUES AND INSERT THOSE VALUES INTO EMP TABLE

CREATE TABLE DUMMY_EMP(EMPNO NUMBER,ENAME VARCHAR2(30),SAL NUMBER, 
JOB VARCHAR2(30),DEPTNO NUMBER)

SELECT * FROM DUMMY_EMP
