/*
CREATE 3 OBJECTS OR DO SEPERATELY IN 3 PROGRAM WINDOWS:

1.CREATE  PACKAGE
GLOBAL VARIABLE

MAKE A COLLECTION VARIABLE INSIDE PACKAGE

2.WRITE A ROW LEVEL TRIGGER
BEFORE DELETE ON KIND OF TRIGGER

SAVE OLD DELETED VALUES

EVERY DELETED ROW MUST BE INSERTED INTO COLLECTION VARIABLE,THAT 
YOU MADE IN THE PACKAGE ,SINCE ITS A GLOBAL VARIABLE

3.WRITE AFTER STATEMENT SEPERATELY,

NOW BRING THAT PACKAGE COLLECTION DATA VIA LOOP AND AGAIN INSERT BACK
INTO EMP TABLE

DO IT IN 3 PROGRAM WINDOWS INDIVIDUALLY
------------------------------------------
--IF DEPTNO CHANGE SHOULD NOT ALLOW
--IF DEPTNO HAS EMP SHOULD NOT ALLOW TO DEL
--AUDIT MAINTAIN

SELECT * FROM AUDIT_DEPT
CREATE TABLE AUDIT_DEPT(DEPTNO NUMBER,OLD_DNAME VARCHAR2(30),NEW_DNAME VARCHAR2(30),
OLD_LOC VARCHAR2(30),NEW_LOC VARCHAR2(30),ACTION_DATE DATE, ACTION_TYPE VARCHAR2(30))
*/
--
/*
SELECT * FROM DEPT
UPDATE DEPT SET DEPTNO = 10 WHERE DEPTNO = 50
DELETE FROM DEPT WHERE DEPTNO = 40
INSERT INTO DEPT(DEPTNO,DNAME,LOC) VALUES(60,'TESTING','CHENNAI');
SELECT * FROM AUDIT_DEPT
UPDATE DEPT SET DNAME = 'DEVELOPING' WHERE DNAME = 'SALES'
UPDATE DEPT SET LOC = 'BANGALORE' WHERE DNAME IN ('HARDWARE','TESTING');
DELETE FROM DEPT WHERE DEPTNO = 60*/
