--FOLLOWS KEYWORD EXAMPLE TRIGGER --trg_follows1,trg_follows2
--SURESH WANTS TO JOIN IN THE COMPANY, RAMESH SHOULD BE PRESENT IN THE COMPANY --trg_emp_not_allow
--IF YOU ARE JOINING NEW EMP YOU SHOULD BE FIRST EMP OF THAT DEPT,THEN ONLY ALLOW--trg_dept_allow_emp

SELECT * FROM EMP
--IF :OLD.ENAME='RAMESH' AND :NEW.ENAME ='SURESH'
INSERT INTO EMP(ENAME) VALUES('SURESH')
