--AT ANY COST SYSTEM SHOULD NOT ALLOW TO REMOVE THE DATA FROM EMP TABLE

CREATE OR REPLACE TRIGGER TRG_DISS3_41
  BEFORE DELETE ON EMP
BEGIN
  RAISE_APPLICATION_ERROR(-20300, 'YOU ARE NOT ALLOWED TO REMOVE EMP DATA');
END;
/
