--SYSTEM SHOULD NOT ALLOW TO TRUNCATE ANY TABLE AT OFFICE CLOSING TIME -- EVEN 6 TO MRNG 6
CREATE OR REPLACE TRIGGER TRG_DISS3_2
  BEFORE DDL ON SCHEMA
BEGIN
  IF ora_sysevent = 'TRUNCATE' AND ora_dict_obj_type = 'TABLE' AND
     TO_CHAR(SYSDATE, 'HH24') NOT BETWEEN 6 AND 17 THEN
    RAISE_APPLICATION_ERROR(-20300,
                            'YOU ARE NOT ALLOWED TO TRUNCATE ANY TABLE AT OFFICE CLOSING TIME');
  END IF;
END;
/
