CREATE OR REPLACE TRIGGER TRG_PKG_EMP_DEL_AFT_STMT
  AFTER DELETE ON EMP
BEGIN
  FOR I IN 1 .. PKG_EMP_DEL.TYP_PKG.COUNT LOOP
    INSERT INTO EMP
      (EMPNO, ENAME, SAL, JOB, DEPTNO)
    VALUES
      (PKG_EMP_DEL.TYP_PKG(I).EMPNO,
       PKG_EMP_DEL.TYP_PKG(I).ENAME,
       PKG_EMP_DEL.TYP_PKG(I).SAL,
       PKG_EMP_DEL.TYP_PKG(I).JOB,
       PKG_EMP_DEL.TYP_PKG(I).DEPTNO);
  END LOOP;
  PKG_EMP_DEL.TYP_PKG.DELETE;
END;
/
