--AT ANY COST SYSTEM SHOULD NOT ALLOW TO REMOVE THE DATA FROM EMP TABLE

CREATE OR REPLACE TRIGGER TRG_DISS3_42
  BEFORE DDL ON SCHEMA
BEGIN
  IF ora_sysevent IN ('TRUNCATE', 'DROP') AND ora_dict_obj_name = 'EMP' THEN
    RAISE_APPLICATION_ERROR(-20300,
                            'YOU ARE NOT ALLOWED TO REMOVE EMP DATA');
  END IF;
END;
/
