--4. IF EMP SAL INCREASED OR DECREASED COMM SHOULD BE UPDATE 20% OF NEW SAL

CREATE OR REPLACE TRIGGER TRG_EMP_COMM_MOD
  BEFORE UPDATE ON EMP
  FOR EACH ROW
BEGIN
  IF :NEW.SAL <> :OLD.SAL THEN
    :NEW.COMM := :NEW.SAL*20/100;
  END IF;
END;
/
