--3. IF EMP SAL IS MODIFIED IT SHOULD BE INCREASE ONLY,
--IF DECREASE FOR ONLY 1OTH DEPT

CREATE OR REPLACE TRIGGER TRG_EMP_SAL_MOD
  BEFORE UPDATE ON EMP
  FOR EACH ROW
BEGIN
   IF
   :NEW.SAL <> :OLD.SAL AND :NEW.SAL <:OLD.SAL AND :NEW.DEPTNO <> 10 THEN
   RAISE_APPLICATION_ERROR(-20300,
                            'NEW SAL MUST BE GREATER THAN OLD SAL FOR 10TH DEPT');
    
  END IF;
END;
/
