--5. IF EMP NAME AND SAL IS MODIFIEID THEN ONLY COMM SHOULD BE CHANGED, 
-- IF ONLY NAME IS CHANGED, SYSTEM SHOULD NOT ALLOW, IF SAL IS MODIFIED, SYSTEM SHOULD NOT ALLOW

CREATE OR REPLACE TRIGGER TRG_EMP_NAME_SAL_MOD
  BEFORE UPDATE ON EMP
  FOR EACH ROW
BEGIN
  IF :NEW.ENAME <> :OLD.ENAME OR :NEW.SAL <> :OLD.SAL THEN
    RAISE_APPLICATION_ERROR(-20300,
                            'YOU ARE NOT ALLOWED TO CHANGE NAME OR SAL');
  END IF;
END;
/
