--2. IF ANY EMP IS JOINING WITHOUT COMM OR MANAGER EMP CANNOT JOIN

CREATE OR REPLACE TRIGGER TRG_NEW_EMP_2
  BEFORE INSERT ON EMP
  FOR EACH ROW
BEGIN
  IF :NEW.COMM=0 OR :NEW.COMM IS NULL OR :NEW.MGR =0 OR :NEW.MGR IS NULL THEN
    RAISE_APPLICATION_ERROR(-20300,
                            'YOU ARE NOT ALLOWED TO JOIN BECAUSE YOUR COMM OR MGR IS NULL');
  END IF;
END;
/
