--1. SYSTEM SHOULD NOT ALLOW TO JOIN NEW EMP IF HIS COMM IS MORE THAN HIS SAL

CREATE OR REPLACE TRIGGER TRG_NEW_EMP
  BEFORE INSERT ON EMP
  FOR EACH ROW
BEGIN
  IF :NEW.COMM > :NEW.SAL THEN
    RAISE_APPLICATION_ERROR(-20300,
                            'YOU ARE NOT ALLOWED TO JOIN BECAUSE YOUR COMM IS MORE THAN SAL');
  END IF;
END;
/
