CREATE OR REPLACE TRIGGER TRG_PKG_EMP_DEL_BEF_ROW
  BEFORE DELETE ON EMP
   FOR EACH ROW 
BEGIN
  PKG_EMP_DEL.TYP_PKG.EXTEND;
  PKG_EMP_DEL.TYP_PKG(PKG_EMP_DEL.TYP_PKG.COUNT).EMPNO := :OLD.EMPNO;
  PKG_EMP_DEL.TYP_PKG(PKG_EMP_DEL.TYP_PKG.COUNT).ENAME := :OLD.ENAME;
  PKG_EMP_DEL.TYP_PKG(PKG_EMP_DEL.TYP_PKG.COUNT).SAL := :OLD.SAL;
  PKG_EMP_DEL.TYP_PKG(PKG_EMP_DEL.TYP_PKG.COUNT).JOB := :OLD.JOB;
  PKG_EMP_DEL.TYP_PKG(PKG_EMP_DEL.TYP_PKG.COUNT).DEPTNO := :OLD.DEPTNO;
END;
/
