--SURESH WANTS TO JOIN IN THE COMPANY, RAMESH SHOULD BE PRESENT IN THE COMPANY 
CREATE OR REPLACE TRIGGER TRG_EMP_NOT_ALLOW
  BEFORE INSERT OR UPDATE ON EMP
  FOR EACH ROW
DECLARE
  X NUMBER;
BEGIN
  IF :NEW.ENAME = 'SURESH' THEN
    SELECT COUNT(*) INTO X FROM EMP WHERE ENAME = 'RAMESH';
  END IF;
  IF X = 0 THEN
    RAISE_APPLICATION_ERROR(-20300,
                            'SURESH WANTS TO JOIN IN THE COMPANY
      ONLY IF RAMESH IS ALREADY WORKING');
  END IF;
END;
/
